package com.hama.leetcode;
/**
Two elements of a binary search tree (BST) are swapped by mistake.

Recover the tree without changing its structure.

Example 1:


Input: [1,3,null,null,2]

&nbsp;  1
&nbsp; /
&nbsp;3
&nbsp; \
&nbsp;  2

Output: [3,1,null,null,2]

&nbsp;  3
&nbsp; /
&nbsp;1
&nbsp; \
&nbsp;  2


Example 2:


Input: [3,1,4,null,null,2]

  3
 / \
1   4
&nbsp;  /
&nbsp; 2

Output: [2,1,4,null,null,3]

  2
 / \
1   4
&nbsp;  /
 &nbsp;3


Follow up:


	A solution using O(n) space is pretty straight forward.
	Could you devise a constant space solution?

**/
_099_Recover_Binary_Search_Tree/_099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_TreeD_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treef_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treef_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treeb_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treey_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree._099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treep_099_Recover_Binary_Search_Treeu_099_Recover_Binary_Search_Treeb_099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Trees_099_Recover_Binary_Search_Trees_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_TreeN_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree{_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treev_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Tree;_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_TreeN_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treef_099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Tree;_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_TreeN_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treeg_099_Recover_Binary_Search_Treeh_099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Tree;_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_TreeN_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree(_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treex_099_Recover_Binary_Search_Tree)_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree{_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treev_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree=_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treex_099_Recover_Binary_Search_Tree;_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree}_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree}_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree*_099_Recover_Binary_Search_Tree/_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Trees_099_Recover_Binary_Search_Trees_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree__099_Recover_Binary_Search_Tree0_099_Recover_Binary_Search_Tree9_099_Recover_Binary_Search_Tree9_099_Recover_Binary_Search_Tree__099_Recover_Binary_Search_TreeR_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treev_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Tree__099_Recover_Binary_Search_TreeB_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treen_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treey_099_Recover_Binary_Search_Tree__099_Recover_Binary_Search_TreeS_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treea_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Treeh_099_Recover_Binary_Search_Tree__099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree{_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treep_099_Recover_Binary_Search_Treeu_099_Recover_Binary_Search_Treeb_099_Recover_Binary_Search_Treel_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treev_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treei_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treec_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treev_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree(_099_Recover_Binary_Search_TreeT_099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_TreeN_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treed_099_Recover_Binary_Search_Treee_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Treer_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treeo_099_Recover_Binary_Search_Treet_099_Recover_Binary_Search_Tree)_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree{_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree _099_Recover_Binary_Search_Tree}_099_Recover_Binary_Search_Tree_099_Recover_Binary_Search_Tree
_099_Recover_Binary_Search_Tree}_099_Recover_Binary_Search_Tree