package com.hama.leetcode;
/**
Given the root of a binary tree with N nodes, each node&nbsp;in the tree has node.val coins, and there are N coins total.

In one move, we may choose two adjacent nodes and move one coin from one node to another.&nbsp; (The move may be from parent to child, or from child to parent.)

Return the number of moves required to make every node have exactly one coin.

&nbsp;


Example 1:




Input: [3,0,0]
Output: 2
Explanation: From the root of the tree, we move one coin to its left child, and one coin to its right child.



Example 2:




Input: [0,3,0]
Output: 3
Explanation: From the left child of the root, we move two coins to the root [taking two moves].  Then, we move one coin from the root of the tree to the right child.



Example 3:




Input: [1,0,2]
Output: 2



Example 4:




Input: [1,0,0,null,3]
Output: 4


&nbsp;

Note:


	1&lt;= N &lt;= 100
	0 &lt;= node.val &lt;= N





**/
_1021_Distribute_Coins_in_Binary_Tree/_1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_TreeD_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treef_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treef_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treeb_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treey_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree._1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treep_1021_Distribute_Coins_in_Binary_Treeu_1021_Distribute_Coins_in_Binary_Treeb_1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treec_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treec_1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_TreeT_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_TreeN_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree{_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treev_1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Tree;_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_TreeT_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_TreeN_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treef_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Tree;_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_TreeT_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_TreeN_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treeg_1021_Distribute_Coins_in_Binary_Treeh_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Tree;_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_TreeT_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_TreeN_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree(_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treex_1021_Distribute_Coins_in_Binary_Tree)_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree{_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treev_1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree=_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treex_1021_Distribute_Coins_in_Binary_Tree;_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree}_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree}_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree*_1021_Distribute_Coins_in_Binary_Tree/_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Treec_1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree__1021_Distribute_Coins_in_Binary_Tree1_1021_Distribute_Coins_in_Binary_Tree0_1021_Distribute_Coins_in_Binary_Tree2_1021_Distribute_Coins_in_Binary_Tree1_1021_Distribute_Coins_in_Binary_Tree__1021_Distribute_Coins_in_Binary_TreeD_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treeb_1021_Distribute_Coins_in_Binary_Treeu_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree__1021_Distribute_Coins_in_Binary_TreeC_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Tree__1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Tree__1021_Distribute_Coins_in_Binary_TreeB_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treea_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treey_1021_Distribute_Coins_in_Binary_Tree__1021_Distribute_Coins_in_Binary_TreeT_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree{_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treep_1021_Distribute_Coins_in_Binary_Treeu_1021_Distribute_Coins_in_Binary_Treeb_1021_Distribute_Coins_in_Binary_Treel_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treec_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treeb_1021_Distribute_Coins_in_Binary_Treeu_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_TreeC_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treei_1021_Distribute_Coins_in_Binary_Treen_1021_Distribute_Coins_in_Binary_Trees_1021_Distribute_Coins_in_Binary_Tree(_1021_Distribute_Coins_in_Binary_TreeT_1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_TreeN_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treed_1021_Distribute_Coins_in_Binary_Treee_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Treer_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treeo_1021_Distribute_Coins_in_Binary_Treet_1021_Distribute_Coins_in_Binary_Tree)_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree{_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree _1021_Distribute_Coins_in_Binary_Tree}_1021_Distribute_Coins_in_Binary_Tree
_1021_Distribute_Coins_in_Binary_Tree}_1021_Distribute_Coins_in_Binary_Tree