package com.hama.leetcode;
/**
Given the root of a binary tree, each node has a value from 0 to 25 representing the letters &#39;a&#39; to &#39;z&#39;: a value of 0 represents &#39;a&#39;, a value of 1 represents &#39;b&#39;, and so on.

Find the lexicographically smallest string that starts at a leaf of this tree and ends at the root.

(As a reminder, any shorter prefix of a string is lexicographically smaller: for example, ab is lexicographically smaller than aba.&nbsp; A leaf of a node is a node that has no children.)



&nbsp;







Example 1:




Input: [0,1,2,3,4,3,4]
Output: dba



Example 2:




Input: [25,1,3,1,3,0,2]
Output: adz



Example 3:




Input: [2,2,1,null,1,0,null,0]
Output: abc


&nbsp;

Note:


	The number of nodes in the given tree will be between 1 and 1000.
	Each node in the tree will have a value between 0 and 25.


&nbsp;



**/
_1030_Smallest_String_Starting_From_Leaf/_1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_LeafD_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaff_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaff_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafb_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafy_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafd_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf._1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafp_1030_Smallest_String_Starting_From_Leafu_1030_Smallest_String_Starting_From_Leafb_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafc_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafc_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_LeafT_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_LeafN_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafd_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf{_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafv_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leaf;_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_LeafT_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_LeafN_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafd_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaff_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leaf;_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_LeafT_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_LeafN_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafd_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafg_1030_Smallest_String_Starting_From_Leafh_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leaf;_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_LeafT_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_LeafN_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafd_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf(_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafx_1030_Smallest_String_Starting_From_Leaf)_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf{_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafv_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf=_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafx_1030_Smallest_String_Starting_From_Leaf;_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf}_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf}_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf*_1030_Smallest_String_Starting_From_Leaf/_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leafc_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf__1030_Smallest_String_Starting_From_Leaf1_1030_Smallest_String_Starting_From_Leaf0_1030_Smallest_String_Starting_From_Leaf3_1030_Smallest_String_Starting_From_Leaf0_1030_Smallest_String_Starting_From_Leaf__1030_Smallest_String_Starting_From_LeafS_1030_Smallest_String_Starting_From_Leafm_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leaf__1030_Smallest_String_Starting_From_LeafS_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leafg_1030_Smallest_String_Starting_From_Leaf__1030_Smallest_String_Starting_From_LeafS_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leafg_1030_Smallest_String_Starting_From_Leaf__1030_Smallest_String_Starting_From_LeafF_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafm_1030_Smallest_String_Starting_From_Leaf__1030_Smallest_String_Starting_From_LeafL_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leaff_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf{_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafp_1030_Smallest_String_Starting_From_Leafu_1030_Smallest_String_Starting_From_Leafb_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafc_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_LeafS_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafi_1030_Smallest_String_Starting_From_Leafn_1030_Smallest_String_Starting_From_Leafg_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leafm_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafl_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafs_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_LeafF_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafm_1030_Smallest_String_Starting_From_LeafL_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafa_1030_Smallest_String_Starting_From_Leaff_1030_Smallest_String_Starting_From_Leaf(_1030_Smallest_String_Starting_From_LeafT_1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_LeafN_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafd_1030_Smallest_String_Starting_From_Leafe_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leafr_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leafo_1030_Smallest_String_Starting_From_Leaft_1030_Smallest_String_Starting_From_Leaf)_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf{_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf _1030_Smallest_String_Starting_From_Leaf}_1030_Smallest_String_Starting_From_Leaf
_1030_Smallest_String_Starting_From_Leaf}_1030_Smallest_String_Starting_From_Leaf