package com.hama.leetcode;
/**
Given a binary tree containing digits from 0-9 only, each root-to-leaf path could represent a number.

An example is the root-to-leaf path 1-&gt;2-&gt;3 which represents the number 123.

Find the total sum of all root-to-leaf numbers.

Note:&nbsp;A leaf is a node with no children.

Example:


Input: [1,2,3]
    1
   / \
  2   3
Output: 25
Explanation:
The root-to-leaf path 1-&gt;2 represents the number 12.
The root-to-leaf path 1-&gt;3 represents the number 13.
Therefore, sum = 12 + 13 = 25.

Example 2:


Input: [4,9,0,5,1]
    4
   / \
  9   0
&nbsp;/ \
5   1
Output: 1026
Explanation:
The root-to-leaf path 4-&gt;9-&gt;5 represents the number 495.
The root-to-leaf path 4-&gt;9-&gt;1 represents the number 491.
The root-to-leaf path 4-&gt;0 represents the number 40.
Therefore, sum = 495 + 491 + 40 = 1026.
**/
_129_Sum_Root_to_Leaf_Numbers/_129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_NumbersD_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbersf_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersf_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersb_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numbersy_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersd_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers._129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersp_129_Sum_Root_to_Leaf_Numbersu_129_Sum_Root_to_Leaf_Numbersb_129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersc_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersc_129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_NumbersT_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersd_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers{_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersv_129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numbers;_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_NumbersT_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersd_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbersf_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers;_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_NumbersT_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersd_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersg_129_Sum_Root_to_Leaf_Numbersh_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers;_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_NumbersT_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersd_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers(_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersx_129_Sum_Root_to_Leaf_Numbers)_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers{_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersv_129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers=_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersx_129_Sum_Root_to_Leaf_Numbers;_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers}_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers}_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers*_129_Sum_Root_to_Leaf_Numbers/_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbersc_129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers__129_Sum_Root_to_Leaf_Numbers1_129_Sum_Root_to_Leaf_Numbers2_129_Sum_Root_to_Leaf_Numbers9_129_Sum_Root_to_Leaf_Numbers__129_Sum_Root_to_Leaf_NumbersS_129_Sum_Root_to_Leaf_Numbersu_129_Sum_Root_to_Leaf_Numbersm_129_Sum_Root_to_Leaf_Numbers__129_Sum_Root_to_Leaf_NumbersR_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers__129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbers__129_Sum_Root_to_Leaf_NumbersL_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbersa_129_Sum_Root_to_Leaf_Numbersf_129_Sum_Root_to_Leaf_Numbers__129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numbersu_129_Sum_Root_to_Leaf_Numbersm_129_Sum_Root_to_Leaf_Numbersb_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers{_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersp_129_Sum_Root_to_Leaf_Numbersu_129_Sum_Root_to_Leaf_Numbersb_129_Sum_Root_to_Leaf_Numbersl_129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersc_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersi_129_Sum_Root_to_Leaf_Numbersn_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numbersu_129_Sum_Root_to_Leaf_Numbersm_129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numbersu_129_Sum_Root_to_Leaf_Numbersm_129_Sum_Root_to_Leaf_Numbersb_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberss_129_Sum_Root_to_Leaf_Numbers(_129_Sum_Root_to_Leaf_NumbersT_129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_NumbersN_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numbersd_129_Sum_Root_to_Leaf_Numberse_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbersr_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numberso_129_Sum_Root_to_Leaf_Numberst_129_Sum_Root_to_Leaf_Numbers)_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers{_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers _129_Sum_Root_to_Leaf_Numbers}_129_Sum_Root_to_Leaf_Numbers_129_Sum_Root_to_Leaf_Numbers
_129_Sum_Root_to_Leaf_Numbers}_129_Sum_Root_to_Leaf_Numbers