package com.hama.leetcode;
/**

Given a collection of intervals, find the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.


Note:

You may assume the interval's end point is always bigger than its start point.
Intervals like [1,2] and [2,3] have borders "touching" but they don't overlap each other.



Example 1:

Input: [ [1,2], [2,3], [3,4], [1,3] ]

Output: 1

Explanation: [1,3] can be removed and the rest of intervals are non-overlapping.



Example 2:

Input: [ [1,2], [1,2], [1,2] ]

Output: 2

Explanation: You need to remove two [1,2] to make the rest of intervals non-overlapping.



Example 3:

Input: [ [1,2], [2,3] ]

Output: 0

Explanation: You don't need to remove any of the intervals since they're already non-overlapping.

**/
_435_Non_overlapping_Intervals/_435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_IntervalsD_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsf_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalso_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsf_435_Non_overlapping_Intervalso_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervals._435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsp_435_Non_overlapping_Intervalsu_435_Non_overlapping_Intervalsb_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsc_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsc_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals _435_Non_overlapping_IntervalsI_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals{_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalss_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals;_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalsd_435_Non_overlapping_Intervals;_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_IntervalsI_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervals(_435_Non_overlapping_Intervals)_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals{_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalss_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals=_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals0_435_Non_overlapping_Intervals;_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalsd_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals=_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals0_435_Non_overlapping_Intervals;_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals}_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_IntervalsI_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervals(_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals,_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalse_435_Non_overlapping_Intervals)_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals{_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalss_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals=_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals;_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalsd_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals=_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalse_435_Non_overlapping_Intervals;_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals}_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals}_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals*_435_Non_overlapping_Intervals/_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervalsc_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals__435_Non_overlapping_Intervals4_435_Non_overlapping_Intervals3_435_Non_overlapping_Intervals5_435_Non_overlapping_Intervals__435_Non_overlapping_IntervalsN_435_Non_overlapping_Intervalso_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervals__435_Non_overlapping_Intervalso_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsp_435_Non_overlapping_Intervalsp_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalsg_435_Non_overlapping_Intervals__435_Non_overlapping_IntervalsI_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals{_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsp_435_Non_overlapping_Intervalsu_435_Non_overlapping_Intervalsb_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsc_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervalse_435_Non_overlapping_IntervalsO_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsp_435_Non_overlapping_IntervalsI_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals(_435_Non_overlapping_IntervalsI_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervals[_435_Non_overlapping_Intervals]_435_Non_overlapping_Intervals _435_Non_overlapping_Intervalsi_435_Non_overlapping_Intervalsn_435_Non_overlapping_Intervalst_435_Non_overlapping_Intervalse_435_Non_overlapping_Intervalsr_435_Non_overlapping_Intervalsv_435_Non_overlapping_Intervalsa_435_Non_overlapping_Intervalsl_435_Non_overlapping_Intervalss_435_Non_overlapping_Intervals)_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals{_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals _435_Non_overlapping_Intervals}_435_Non_overlapping_Intervals
_435_Non_overlapping_Intervals}_435_Non_overlapping_Intervals