package com.hama.leetcode;
/**

Given a binary tree, find the leftmost value in the last row of the tree. 


Example 1:

Input:

    2
   / \
  1   3

Output:
1



  Example 2: 

Input:

        1
       / \
      2   3
     /   / \
    4   5   6
       /
      7

Output:
7



Note:
You may assume the tree (i.e., the given root node) is not NULL.
**/
_513_Find_Bottom_Left_Tree_Value/_513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_ValueD_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuef_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuef_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valueb_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuey_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value._513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuep_513_Find_Bottom_Left_Tree_Valueu_513_Find_Bottom_Left_Tree_Valueb_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuec_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuec_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Values_513_Find_Bottom_Left_Tree_Values_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_ValueT_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_ValueN_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value{_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuev_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Value;_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_ValueT_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_ValueN_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuef_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value;_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_ValueT_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_ValueN_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valueg_513_Find_Bottom_Left_Tree_Valueh_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value;_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_ValueT_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_ValueN_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value(_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuex_513_Find_Bottom_Left_Tree_Value)_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value{_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuev_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value=_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuex_513_Find_Bottom_Left_Tree_Value;_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value}_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value}_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value*_513_Find_Bottom_Left_Tree_Value/_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Valuec_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Values_513_Find_Bottom_Left_Tree_Values_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value__513_Find_Bottom_Left_Tree_Value5_513_Find_Bottom_Left_Tree_Value1_513_Find_Bottom_Left_Tree_Value3_513_Find_Bottom_Left_Tree_Value__513_Find_Bottom_Left_Tree_ValueF_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Value__513_Find_Bottom_Left_Tree_ValueB_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuem_513_Find_Bottom_Left_Tree_Value__513_Find_Bottom_Left_Tree_ValueL_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuef_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value__513_Find_Bottom_Left_Tree_ValueT_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value__513_Find_Bottom_Left_Tree_ValueV_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valueu_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value{_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuep_513_Find_Bottom_Left_Tree_Valueu_513_Find_Bottom_Left_Tree_Valueb_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuec_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuef_513_Find_Bottom_Left_Tree_Valuei_513_Find_Bottom_Left_Tree_Valuen_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_ValueB_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuem_513_Find_Bottom_Left_Tree_ValueL_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuef_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_ValueV_513_Find_Bottom_Left_Tree_Valuea_513_Find_Bottom_Left_Tree_Valuel_513_Find_Bottom_Left_Tree_Valueu_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value(_513_Find_Bottom_Left_Tree_ValueT_513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_ValueN_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valued_513_Find_Bottom_Left_Tree_Valuee_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Valuer_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valueo_513_Find_Bottom_Left_Tree_Valuet_513_Find_Bottom_Left_Tree_Value)_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value{_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value _513_Find_Bottom_Left_Tree_Value}_513_Find_Bottom_Left_Tree_Value
_513_Find_Bottom_Left_Tree_Value}_513_Find_Bottom_Left_Tree_Value