package com.hama.leetcode;
/**
Given a binary tree, write a function to get the maximum width of the given tree. The width of a tree is the maximum width among all levels. The binary tree has the same structure as a full binary tree, but some nodes are null.

The width of one level is defined as the length between the end-nodes (the leftmost and right most non-null nodes in the level, where the null nodes between the end-nodes are also counted into the length calculation.

Example 1:


Input: 

           1
         /   \
        3     2
       / \     \  
      5   3     9 

Output: 4
Explanation: The maximum width existing in the third level with the length 4 (5,3,null,9).


Example 2:


Input: 

          1
         /  
        3    
       / \       
      5   3     

Output: 2
Explanation: The maximum width existing in the third level with the length 2 (5,3).


Example 3:


Input: 

          1
         / \
        3   2 
       /        
      5      

Output: 2
Explanation: The maximum width existing in the second level with the length 2 (3,2).


Example 4:


Input: 

          1
         / \
        3   2
       /     \  
      5       9 
     /         \
    6           7
Output: 8
Explanation:The maximum width existing in the fourth level with the length 8 (6,null,null,null,null,null,null,7).




Note: Answer will in the range of 32-bit signed integer.
**/
_662_Maximum_Width_of_Binary_Tree/_662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_TreeD_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treef_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treef_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treeb_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treey_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree._662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treep_662_Maximum_Width_of_Binary_Treeu_662_Maximum_Width_of_Binary_Treeb_662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treec_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treec_662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Trees_662_Maximum_Width_of_Binary_Trees_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_TreeN_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree{_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treev_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Tree;_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_TreeN_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treef_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Tree;_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_TreeN_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treeg_662_Maximum_Width_of_Binary_Treeh_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Tree;_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_TreeN_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree(_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treex_662_Maximum_Width_of_Binary_Tree)_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree{_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treev_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree=_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treex_662_Maximum_Width_of_Binary_Tree;_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree}_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree}_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree*_662_Maximum_Width_of_Binary_Tree/_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Treec_662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Trees_662_Maximum_Width_of_Binary_Trees_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree__662_Maximum_Width_of_Binary_Tree6_662_Maximum_Width_of_Binary_Tree6_662_Maximum_Width_of_Binary_Tree2_662_Maximum_Width_of_Binary_Tree__662_Maximum_Width_of_Binary_TreeM_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Treex_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treem_662_Maximum_Width_of_Binary_Treeu_662_Maximum_Width_of_Binary_Treem_662_Maximum_Width_of_Binary_Tree__662_Maximum_Width_of_Binary_TreeW_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Treeh_662_Maximum_Width_of_Binary_Tree__662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treef_662_Maximum_Width_of_Binary_Tree__662_Maximum_Width_of_Binary_TreeB_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treey_662_Maximum_Width_of_Binary_Tree__662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree{_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treep_662_Maximum_Width_of_Binary_Treeu_662_Maximum_Width_of_Binary_Treeb_662_Maximum_Width_of_Binary_Treel_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treec_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treew_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Treeh_662_Maximum_Width_of_Binary_TreeO_662_Maximum_Width_of_Binary_Treef_662_Maximum_Width_of_Binary_TreeB_662_Maximum_Width_of_Binary_Treei_662_Maximum_Width_of_Binary_Treen_662_Maximum_Width_of_Binary_Treea_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treey_662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree(_662_Maximum_Width_of_Binary_TreeT_662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_TreeN_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treed_662_Maximum_Width_of_Binary_Treee_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Treer_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treeo_662_Maximum_Width_of_Binary_Treet_662_Maximum_Width_of_Binary_Tree)_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree{_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree _662_Maximum_Width_of_Binary_Tree}_662_Maximum_Width_of_Binary_Tree_662_Maximum_Width_of_Binary_Tree
_662_Maximum_Width_of_Binary_Tree}_662_Maximum_Width_of_Binary_Tree