package com.hama.leetcode;
/**
Given a non-empty, singly&nbsp;linked list with head node head, return&nbsp;a&nbsp;middle node of linked list.

If there are two middle nodes, return the second middle node.

&nbsp;


Example 1:


Input: [1,2,3,4,5]
Output: Node 3 from this list (Serialization: [3,4,5])
The returned node has value 3.  (The judge&#39;s serialization of this node is [3,4,5]).
Note that we returned a ListNode object ans, such that:
ans.val = 3, ans.next.val = 4, ans.next.next.val = 5, and ans.next.next.next = NULL.



Example 2:


Input: [1,2,3,4,5,6]
Output: Node 4 from this list (Serialization: [4,5,6])
Since the list has two middle nodes with values 3 and 4, we return the second one.


&nbsp;

Note:


	The number of nodes in the given list will be between 1&nbsp;and 100.



**/
_908_Middle_of_the_Linked_List/_908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_ListD_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_Listf_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listf_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listr_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Listg_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Listy_908_Middle_of_the_Linked_List-_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Listk_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_List._908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listp_908_Middle_of_the_Linked_Listu_908_Middle_of_the_Linked_Listb_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listc_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listc_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Lista_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_ListN_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List{_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listv_908_Middle_of_the_Linked_Lista_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_List;_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_ListN_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_Listx_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_List;_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_ListN_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List(_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listx_908_Middle_of_the_Linked_List)_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List{_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listv_908_Middle_of_the_Linked_Lista_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List=_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listx_908_Middle_of_the_Linked_List;_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List}_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List}_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List*_908_Middle_of_the_Linked_List/_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_Listc_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Lista_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List__908_Middle_of_the_Linked_List9_908_Middle_of_the_Linked_List0_908_Middle_of_the_Linked_List8_908_Middle_of_the_Linked_List__908_Middle_of_the_Linked_ListM_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List__908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listf_908_Middle_of_the_Linked_List__908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_Listh_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List__908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listn_908_Middle_of_the_Linked_Listk_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_List__908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List{_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listp_908_Middle_of_the_Linked_Listu_908_Middle_of_the_Linked_Listb_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listc_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_ListN_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listm_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Listl_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_ListN_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List(_908_Middle_of_the_Linked_ListL_908_Middle_of_the_Linked_Listi_908_Middle_of_the_Linked_Lists_908_Middle_of_the_Linked_Listt_908_Middle_of_the_Linked_ListN_908_Middle_of_the_Linked_Listo_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_Listh_908_Middle_of_the_Linked_Liste_908_Middle_of_the_Linked_Lista_908_Middle_of_the_Linked_Listd_908_Middle_of_the_Linked_List)_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List{_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List _908_Middle_of_the_Linked_List}_908_Middle_of_the_Linked_List
_908_Middle_of_the_Linked_List}_908_Middle_of_the_Linked_List