package com.hama.leetcode;
/**
Given a tree, rearrange the tree in in-order so that the leftmost node in the tree is now the root of the tree, and every node has no left child and only 1 right child.


Example 1:
Input: [5,3,6,2,4,null,8,1,null,null,null,7,9]

       5
      / \
    3    6
   / \    \
  2   4    8
&nbsp;/        / \ 
1        7   9

Output: [1,null,2,null,3,null,4,null,5,null,6,null,7,null,8,null,9]

 1
&nbsp; \
&nbsp;  2
&nbsp;   \
&nbsp;    3
&nbsp;     \
&nbsp;      4
&nbsp;       \
&nbsp;        5
&nbsp;         \
&nbsp;          6
&nbsp;           \
&nbsp;            7
&nbsp;             \
&nbsp;              8
&nbsp;               \
                 9  

Note:


	The number of nodes in the given tree will be between 1 and 100.
	Each node will have a unique integer value from 0 to 1000.

**/
_933_Increasing_Order_Search_Tree/_933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_TreeD_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treef_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treef_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treeb_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treey_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree._933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treep_933_Increasing_Order_Search_Treeu_933_Increasing_Order_Search_Treeb_933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Trees_933_Increasing_Order_Search_Trees_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_TreeN_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree{_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treev_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Tree;_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_TreeN_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treef_933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Tree;_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_TreeN_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treeg_933_Increasing_Order_Search_Treeh_933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Tree;_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_TreeN_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree(_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treex_933_Increasing_Order_Search_Tree)_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree{_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treev_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree=_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treex_933_Increasing_Order_Search_Tree;_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree}_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree}_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree*_933_Increasing_Order_Search_Tree/_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Trees_933_Increasing_Order_Search_Trees_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree__933_Increasing_Order_Search_Tree9_933_Increasing_Order_Search_Tree3_933_Increasing_Order_Search_Tree3_933_Increasing_Order_Search_Tree__933_Increasing_Order_Search_TreeI_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Trees_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treeg_933_Increasing_Order_Search_Tree__933_Increasing_Order_Search_TreeO_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Tree__933_Increasing_Order_Search_TreeS_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Treeh_933_Increasing_Order_Search_Tree__933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree{_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treep_933_Increasing_Order_Search_Treeu_933_Increasing_Order_Search_Treeb_933_Increasing_Order_Search_Treel_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_TreeN_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treec_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treea_933_Increasing_Order_Search_Trees_933_Increasing_Order_Search_Treei_933_Increasing_Order_Search_Treen_933_Increasing_Order_Search_Treeg_933_Increasing_Order_Search_TreeB_933_Increasing_Order_Search_TreeS_933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Tree(_933_Increasing_Order_Search_TreeT_933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_TreeN_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treed_933_Increasing_Order_Search_Treee_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Treer_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treeo_933_Increasing_Order_Search_Treet_933_Increasing_Order_Search_Tree)_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree{_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree _933_Increasing_Order_Search_Tree}_933_Increasing_Order_Search_Tree_933_Increasing_Order_Search_Tree
_933_Increasing_Order_Search_Tree}_933_Increasing_Order_Search_Tree